# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djorm_pgarray.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0044_auto_20160531_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidays', djorm_pgarray.fields.DateArrayField(dbtype='date', default=[], verbose_name='days ignored in burndown')),
                ('is_ignoring_weekends', models.NullBooleanField(default=False, verbose_name='is ignoring weekends')),
                ('is_ignoring_days', models.NullBooleanField(default=False, verbose_name='is ignoring specific days')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_holidays', to='projects.Project', verbose_name='project')),
            ],
            options={
                'ordering': ['project'],
                'verbose_name': 'bank holidays',
                'verbose_name_plural': 'bank holidays',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidays', djorm_pgarray.fields.DateArrayField(dbtype='date', default=[], verbose_name='days ignored in burndown')),
                ('max_days', models.PositiveIntegerField(blank=True, default=23, null=True, verbose_name='maximum days of holidays per year')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_holidays', to='projects.Project', verbose_name='project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_holidays', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['project'],
                'verbose_name': 'user holidays',
                'verbose_name_plural': 'user holidays',
                'abstract': False,
            },
        ),
    ]
