# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djorm_pgarray.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0040_remove_memberships_of_cancelled_users_acounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ignoring_weekends', models.NullBooleanField(default=False, verbose_name='is ignoring weekends')),
                ('is_ignoring_days', models.NullBooleanField(default=False, verbose_name='is ignoring specific days')),
                ('days_ignored', djorm_pgarray.fields.DateTimeArrayField(dbtype='timestamp with time zone', default=[], verbose_name='days ignored in burndown')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_holidays', to='projects.Project')),
            ],
        ),
    ]
