# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-18 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ignoring_weekends', models.NullBooleanField(default=False, verbose_name='is ignoring weekends')),
                ('is_ignoring_days', models.NullBooleanField(default=False, verbose_name='is ignoring specific days')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_holidays', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DateIgnored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True, verbose_name='day ignored in burndown')),
                ('bank_holidays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_ignored', to='taiga_contrib_holidays.BankHolidays')),
            ],
        ),
    ]
